version: '3'

# postgres
# docker container run \
# -d \
# --name postgres-db \
# -e POSTGRES_PASSWORD=123456 \
# -v postgres-db:/PATH/DE/LA/BASE/DE/DATOS \
# postgres:15.1

# pgAdmin
# docker container run \
# --name pgAdmin \
# -e PGADMIN_DEFAULT_PASSWORD=123456 \
# -e PGADMIN_DEFAULT_EMAIL=superman@google.com \
# -dp 8080:80 \
# dpage/pgadmin4:6.17

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data #ejemplo
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

# volumes:
#   postgres-db:
#     external: true
